# Generated by Django 3.2.6 on 2021-08-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_Link', models.CharField(max_length=255, null=True)),
                ('Series_Title', models.CharField(max_length=255, null=True)),
                ('Released_Year', models.IntegerField(null=True)),
                ('Certificate', models.CharField(max_length=255, null=True)),
                ('Runtime', models.CharField(max_length=255, null=True)),
                ('Genre', models.CharField(max_length=255, null=True)),
                ('IMDB_Rating', models.CharField(max_length=255, null=True)),
                ('Overview', models.CharField(max_length=255, null=True)),
                ('Meta_score', models.CharField(max_length=255, null=True)),
                ('Director', models.CharField(max_length=255, null=True)),
                ('Star1', models.CharField(max_length=255, null=True)),
                ('Star2', models.CharField(max_length=255, null=True)),
                ('Star3', models.CharField(max_length=255, null=True)),
                ('Star4', models.CharField(max_length=255, null=True)),
                ('No_of_Votes', models.IntegerField(null=True)),
                ('Gross', models.CharField(max_length=255, null=True)),
                ('movieId', models.CharField(max_length=255, null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
